### PR TITLE
Use babel options from webpack config like babel-loader do

### PR DESCRIPTION
**Pull request by vslinko**

### CODE REVIEW

**Comment by atondelier** [comment]
:+1: Passing babel options is definitely needed. But, directly reading into `options.babel` may be the fallback for reading into a `options.isparta` object.

**Comment by vslinko** [comment]
@atondelier are you sure that someone needs different babel config for isparta?

**Comment by vslinko** [comment]
@deepsweet what are you think?

**Comment by atondelier** [comment]
@vslinko I agree it will be the same most of the time. I suggested that only for flexibility, e.g. if you want a specific `shouldPrintComment` babel callback for isparta instrumenter.

**Comment by vslinko** [comment]
@atondelier Updated PR.

**Pull request merged**
